### ISSUE TITLE
Bug: Properties in object callbacks aren't accessible due to 'internal' protection level

### ISSUE THREAD

**Issue by javierjm** [afterpay/sdk-ios#183]
# 🌎 Environment

 - OS Version: iOS  14.4
 - Version/Commit: 97ac392

# 💬 Description
When implementing the following callbacks I'm not able to access `Address` and `ShippingOption` properties to compare with my app data model, so I can't react when user select a new shipping option for example: 

shippingOption.name: throws the following error:  `'name' is inaccessible due to 'internal' protection level`

```
  func shippingAddressDidChange(address: Address, completion: @escaping ShippingOptionsCompletion) {
    // Use the address to form a shipping options result and pass to completion
  }
```

```
  func shippingOptionDidChange(shippingOption: ShippingOption) {
    // Optionally update your application model with the selected shipping option
  }
```

# 🦶 Reproduction Steps

1. On the attached project Example.
2. Open `sdk-ios-master/Example/Example/Purchase/CheckoutHandler.swift` 
3. Go to `func shippingOptionDidChange(shippingOption: ShippingOption) `
4. Add this to the boby of that func: `let name = shippingOption.name`

# 🤔 Expected Results

App should compile and allow user to get shippingOption `name`

# 😲 Actual Results

App is throwing an error: `'name' is inaccessible due to 'internal' protection level` 
this method is useless if consumer can't access these properties, they should be public. 

## 📄 Stack Traces

```
Include a stack trace if applicable...
```

## 🌳 Logs

```
Include any logs if applicable...
```

# 🤝 Related Issues

Related PRs, Issues, Links:
- #xxx, #yyy

**Comment by EvgenyKarkan** [comment]
Cannot disagree on this, `ShippingAddress`, `ShippingOption` properties must be `public`.

Also, the +1 must-have thing would be adding a second argument to the `shippingOptionDidChange` callback where we (SDK clients) can put the final order amount data so AfterPay UI can reflect it.

Use case: 
- user selects shipping option;
- client app does a service call in order to update the cart; 
- cart gets updated with order amount & tax amount;
- client app passes it to the SDK;
- SDK shows the same amounts to a user as a client app.

**Comment by huwr-afterpay** [comment]
Hi @javierjm  Thanks for this excellent bug report. I will fix this today.
