### ISSUE TITLE
Bug: `shippingOptionDidChange` closure has a 5-second timeout

### ISSUE THREAD

**Issue by rcbello** [afterpay/sdk-ios#241]
# 🌎 Environment

 - OS Version: iOS 16.2.0
 - Version/Commit: 5.2.0
 - Environment: Sandbox / Development

# 💬 Description
This is more of an inquiry than a bug report.
`shippingOptionDidChange` closure has a 5-second timeout. Afterpay express checkout UI shows an error after the timeout. If we do a network request inside the closure and wait for it to complete before calling completion, it can very easily go over the timeout.
Is doing a network request inside `shippingOptionDidChange` discouraged?

# 🦶 Reproduction Steps
Do a network request inside `shippingOptionDidChange` closure before calling completion. If network request takes more than 5 seconds Afterpay UI shows an error.

## Screenshots
![208795864-84d62182-ccb2-4937-91eb-3cc16c4b403e](https://user-images.githubusercontent.com/5111147/216589162-a5e8dd43-e27b-4b96-b10d-638c64253679.png)

**Comment by ScottAntonacAP** [comment]
Hi @rcbello,

Thank you for your enquiry.

Just to clarify, the 5 second timeout is built into the checkout (WebView) rather than the `shippingOptionDidChange` closure. The closure was built so that a single shipping option could be updated if necessary via a network call. The 5 second limit was implemented so that if the merchant endpoint is unresponsive, the consumer is given some feedback and a chance to recover.

With regard to your specific enquiry:

> Is doing a network request inside `shippingOptionDidChange` discouraged?

The answer is no, it is not discouraged, the thought being that retrieving details for a single option should be manageable within the 5 second limit.

**Comment by rcbello** [comment]
Thank you for the clarification, @ScottAntonacAP!

Is there a way to increase the timeout? For our instance, we also need to calculate the tax within the network call which entails calling a third party service and it sometimes takes just a bit more than 5 seconds.

**Comment by ScottAntonacAP** [comment]
Thanks again for your message, @rcbello. This is currently being discussed internally with the checkout team. Any further updates on this topic will be posted here.

**Comment by rcbello** [comment]
Thanks again! Looking forward to the update.

**Comment by ScottAntonacAP** [comment]
Hi @rcbello,

After the internal discussions, the team have decided to consider increasing the timeout for this callback at the web checkout level, depending on the requirements. Could you please provide us with some guidance on the timeout you’re expecting for the 99th percentile?

Please note that from our experience we have seen that whenever we increase the time a customer has to wait in checkout, it increases the rate of customer drop off. We would suggest finding a way to improve times to retrieve the data - for example caching the response from the 3rd-party service.

Thank you.

**Comment by rcbello** [comment]
Hi @ScottAntonacAP, from our performance logs, 95th percentile has over-all response time of 6.12s. I think 7 seconds should cover the 99th percentile of requests.
Yup, we're also looking the performance improvements for our requests, but have only decreased the times by a small amount at the moment.

**Comment by ScottAntonacAP** [comment]
Hi @rcbello 

After another chat with the checkout team, they are happy to make the change to 7 seconds. The aim is to make get the change out in the next release. Once it is in place, another post will be made below.

The `bug` label has been removed from this issue as the change does not relate to the SDK and the current timeout is expected behaviour.

Thanks again.

**Comment by ScottAntonacAP** [comment]
Hi @rcbello 

Wanted to let you know that the timeout change has been made and merged in. The timeout has been increased to 7 seconds.

Thank you.
